/**
 * Worm API
 * Worm tunnel protocol - Secure API for managing projects and user data
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Project element data transfer object
 */
export interface ProjectElementDto { 
    /**
     * Unique identifier of the element
     */
    id?: string;
    /**
     * Name of the element
     */
    name: string;
    /**
     * Type of the element (FOLDER/ITEM)
     */
    type: ProjectElementDto.TypeEnum;
    /**
     * ID of the parent element
     */
    parentId?: string;
    /**
     * Position for ordering siblings
     */
    position?: number;
    /**
     * Whether the element can be expanded (computed from type)
     */
    expandable?: boolean;
    /**
     * Level in the tree (computed from parent relationships)
     */
    level?: number;
}
export namespace ProjectElementDto {
    export type TypeEnum = 'FOLDER' | 'ITEM';
    export const TypeEnum = {
        Folder: 'FOLDER' as TypeEnum,
        Item: 'ITEM' as TypeEnum
    };
}


