/**
 * Worm API
 * worm tunnel protocol
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Project { 
    id?: string;
    title?: string;
    description?: string;
    userId?: string;
    status?: string;
    createdDate?: string;
    updatedDate?: string;
    chapters?: Array<string>;
    tags?: Array<string>;
}

