/**
 * Worm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


/**
 * Project Data
 */
export interface Project { 
    /**
     * Project ID
     */
    id?: number;
    /**
     * Project slug
     */
    slug?: string;
    /**
     * Project title
     */
    title?: string;
    /**
     * Project description
     */
    description?: string;
    user?: User;
    /**
     * Date when the project was created
     */
    createdDate?: string;
    /**
     * Date when the project was last updated
     */
    updatedDate?: string;
}

