/**
 * Worm API
 * worm tunnel protocol
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User information
 */
export interface UserDto { 
    /**
     * Username
     */
    username?: string;
    /**
     * User\'s name
     */
    name?: string;
    /**
     * URL of the user\'s avatar image
     */
    avatarImageUrl?: string;
}

