#!/usr/bin/env bun
/// <reference types="bun-types" />
/**
 * Build script for creating a standalone Inkweld binary with embedded frontend
 *
 * This script:
 * 1. Checks if frontend is built
 * 2. Collects all frontend assets
 * 3. Builds a single executable with backend + embedded frontend
 *
 * Usage: bun run build:binary:full
 */

import { readdirSync, statSync, existsSync } from 'node:fs';
import { join, resolve, relative } from 'node:path';

const PROJECT_ROOT = resolve(import.meta.dir, '../..');
const FRONTEND_DIST = join(PROJECT_ROOT, 'frontend/dist/browser');
const BACKEND_SRC = join(PROJECT_ROOT, 'backend/src/bun-runner.ts');
const OUTPUT_FILE = join(PROJECT_ROOT, 'backend/dist/inkweld');

console.log('🚀 Building Inkweld standalone binary with embedded frontend\n');

// Step 1: Check if frontend is built
console.log('📦 Checking frontend build...');
if (!existsSync(FRONTEND_DIST)) {
  console.error('❌ Frontend not built. Please run: cd frontend && bun run build');
  process.exit(1);
}

const indexHtmlPath = join(FRONTEND_DIST, 'index.html');
if (!existsSync(indexHtmlPath)) {
  console.error('❌ Frontend build incomplete (missing index.html)');
  process.exit(1);
}

console.log('✅ Frontend build found\n');

// Step 2: Collect all frontend files
console.log('📂 Collecting frontend assets...');
const frontendFiles: string[] = [];

function collectFiles(dir: string) {
  const entries = readdirSync(dir);
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      collectFiles(fullPath);
    } else {
      frontendFiles.push(fullPath);
    }
  }
}

collectFiles(FRONTEND_DIST);

console.log(`✅ Found ${frontendFiles.length} frontend files\n`);

// Step 3: Generate TypeScript import file for all assets
console.log('📝 Generating asset imports file...');

const TEMP_IMPORTS_FILE = join(PROJECT_ROOT, 'backend/src/.frontend-imports-generated.ts');
const imports = frontendFiles.map((file, idx) => {
  const relativePath = relative(join(PROJECT_ROOT, 'backend/src'), file).replaceAll('\\', '/');
  const varName = `asset_${idx}`;
  return `import ${varName} from '${relativePath}' with { type: 'file' };`;
});

const assetMap = frontendFiles.map((file, idx) => {
  const relativePath = relative(join(PROJECT_ROOT, 'frontend/dist/browser'), file).replace(
    /\\/g,
    '/'
  );
  return `  assets.set('${relativePath}', asset_${idx});`;
});

const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by build-binary-full.ts
 * This file imports all frontend assets for embedding in the binary
 */

${imports.join('\n')}

export function getAllFrontendAssets(): Map<string, string> {
  const assets = new Map<string, string>();
${assetMap.join('\n')}
  return assets;
}
`;

await Bun.write(TEMP_IMPORTS_FILE, fileContent);
console.log(`✅ Generated imports file with ${frontendFiles.length} assets\n`);

// Step 4: Build the binary with embedded assets
console.log('🔨 Building binary with embedded frontend...');
console.log(`   Backend source: ${BACKEND_SRC}`);
console.log(`   Frontend assets: ${frontendFiles.length} files imported\n`);

const buildArgs = [
  'build',
  '--compile',
  '--minify',
  '--sourcemap',
  BACKEND_SRC,
  '--outfile',
  OUTPUT_FILE,
];

console.log(`Running: bun ${buildArgs.join(' ')}\n`);

const result = Bun.spawnSync(['bun', ...buildArgs], {
  stdout: 'inherit',
  stderr: 'inherit',
  cwd: PROJECT_ROOT,
});

if (result.exitCode !== 0) {
  console.error('\n❌ Build failed');
  process.exit(result.exitCode || 1);
}

// Step 4: Verify the output
if (!existsSync(OUTPUT_FILE)) {
  console.error('\n❌ Binary not created');
  process.exit(1);
}

const stats = statSync(OUTPUT_FILE);
const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);

console.log('\n✅ Build successful!');
console.log(`📦 Binary: ${OUTPUT_FILE}`);
console.log(`📊 Size: ${sizeMB} MB`);
console.log(`📁 Embedded: ${frontendFiles.length} frontend files`);
console.log('\n💡 Test the binary:');
console.log(`   ./backend/dist/inkweld-backend`);
console.log('\n🚀 The binary includes:');
console.log('   • Bun runtime');
console.log('   • Backend API server');
console.log('   • Complete Angular frontend');
console.log('   • All static assets');
