#!/usr/bin/env bun
/// <reference types="bun-types" />
/**
 * Generate frontend imports file for binary embedding
 *
 * This script scans the frontend dist directory and generates a TypeScript file
 * that imports all assets with { type: 'file' } for Bun's binary embedding.
 *
 * Usage: bun run scripts/generate-frontend-imports.ts
 *
 * This is called automatically by the Dockerfile after copying frontend dist,
 * and also by build-binary-full.ts for local development.
 */

import { readdirSync, statSync, existsSync } from 'node:fs';
import { join, resolve, relative } from 'node:path';

const PROJECT_ROOT = resolve(import.meta.dir, '../..');
const FRONTEND_DIST = join(PROJECT_ROOT, 'frontend/dist/browser');
const OUTPUT_FILE = join(PROJECT_ROOT, 'backend/src/.frontend-imports-generated.ts');

console.log('📝 Generating frontend imports file...');

// Check if frontend is built
if (!existsSync(FRONTEND_DIST)) {
  console.error('❌ Frontend not built. Please run: cd frontend && bun run build');
  process.exit(1);
}

const indexHtmlPath = join(FRONTEND_DIST, 'index.html');
if (!existsSync(indexHtmlPath)) {
  console.error('❌ Frontend build incomplete (missing index.html)');
  process.exit(1);
}

// Collect all frontend files recursively
const frontendFiles: string[] = [];

function collectFiles(dir: string) {
  const entries = readdirSync(dir);
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      collectFiles(fullPath);
    } else {
      frontendFiles.push(fullPath);
    }
  }
}

collectFiles(FRONTEND_DIST);

console.log(`   Found ${frontendFiles.length} frontend files`);

// Generate import statements
const imports = frontendFiles.map((file, idx) => {
  const relativePath = relative(join(PROJECT_ROOT, 'backend/src'), file).replace(/\\/g, '/');
  const varName = `asset_${idx}`;
  return `import ${varName} from '${relativePath}' with { type: 'file' };`;
});

// Generate asset map entries
const assetMap = frontendFiles.map((file, idx) => {
  const relativePath = relative(join(PROJECT_ROOT, 'frontend/dist/browser'), file).replace(
    /\\/g,
    '/'
  );
  return `  assets.set('${relativePath}', asset_${idx});`;
});

const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate-frontend-imports.ts
 * This file imports all frontend assets for embedding in the binary
 */

${imports.join('\n')}

export function getAllFrontendAssets(): Map<string, string> {
  const assets = new Map<string, string>();
${assetMap.join('\n')}
  return assets;
}
`;

await Bun.write(OUTPUT_FILE, fileContent);
console.log(`✅ Generated ${OUTPUT_FILE}`);
console.log(`   ${frontendFiles.length} assets ready for embedding`);
