/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminProjectStorage } from './admin-project-storage';

export interface AdminUserProjects {
  /**
   * User id
   */
  userId: string;
  /**
   * User username
   */
  username: string;
  projects: Array<AdminProjectStorage>;
  /**
   * Sum of dataBytes across projects
   */
  totalDataBytes: number;
  /**
   * Sum of mediaBytes across projects
   */
  totalMediaBytes: number;
  /**
   * Sum of totalBytes across projects
   */
  totalBytes: number;
  /**
   * Per-user override in bytes (null = instance default)
   */
  syncQuotaBytes: number | null;
  /**
   * Allowance actually in force
   */
  effectiveQuotaBytes: number;
  /**
   * Instance-wide default when no override is set
   */
  instanceDefaultQuotaBytes: number;
}
