/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminImageModelProfile { 
    id: string;
    name: string;
    description: string | null;
    /**
     * Image generation provider
     */
    provider: AdminImageModelProfileProvider;
    modelId: string;
    enabled: boolean;
    supportsImageInput: boolean;
    supportsCustomResolutions: boolean;
    usesAspectRatioOnly: boolean;
    supportedSizes: Array<string> | null;
    defaultSize: string | null;
    sortOrder: number;
    /**
     * Credit cost per generation (whole numbers)
     */
    creditCost: number;
    modelConfig: { [key: string]: any | null; } | null;
    createdAt: string;
    updatedAt: string;
}
export enum AdminImageModelProfileProvider {
    Openai = 'openai',
    Openrouter = 'openrouter',
    Falai = 'falai',
    StableDiffusion = 'stable-diffusion'
};



