/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AutoReviewSuggestion { 
    /**
     * Unique suggestion ID
     */
    id: string;
    /**
     * Explanation
     */
    message: string;
    /**
     * Suggested replacement
     */
    suggestion: string;
    /**
     * Error category
     */
    category: string;
    /**
     * Severity level
     */
    severity: AutoReviewSuggestionSeverity;
    /**
     * Start offset in paragraph
     */
    paragraphStart: number;
    /**
     * End offset in paragraph
     */
    paragraphEnd: number;
    /**
     * Original text with the issue
     */
    originalText: string;
}
export enum AutoReviewSuggestionSeverity {
    Error = 'error',
    Warning = 'warning',
    Suggestion = 'suggestion'
};



