/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BackgroundPreference {
  /**
   * default follows the admin setting, preset uses a built-in, upload uses the user\'s own image.
   */
  kind: BackgroundPreferenceKind;
  /**
   * Required when kind is `preset`.
   */
  presetId?: BackgroundPreferencePresetId;
}
export enum BackgroundPreferenceKind {
  Default = 'default',
  Preset = 'preset',
  Upload = 'upload',
}
export enum BackgroundPreferencePresetId {
  Bundled = 'bundled',
  Midnight = 'midnight',
  Dusk = 'dusk',
  Forest = 'forest',
  Parchment = 'parchment',
  Slate = 'slate',
  None = 'none',
}
