/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsentRequestGrantsInner { 
    projectId: string;
    role: ConsentRequestGrantsInnerRole;
}
export enum ConsentRequestGrantsInnerRole {
    Viewer = 'viewer',
    Editor = 'editor',
    Admin = 'admin'
};



