/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { McpPermission } from './mcp-permission';


export interface CreateMcpKeyRequest { 
    /**
     * Friendly name for the key
     */
    name: string;
    /**
     * Permissions to grant
     */
    permissions: Array<McpPermission>;
    /**
     * Expiration timestamp (ms since epoch)
     */
    expiresAt?: number;
}

