/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateImageModelProfileRequest { 
    /**
     * Display name for the profile
     */
    name: string;
    /**
     * Optional description
     */
    description?: string;
    /**
     * Image generation provider
     */
    provider: CreateImageModelProfileRequestProvider;
    /**
     * Provider-specific model identifier
     */
    modelId: string;
    enabled?: boolean;
    supportsImageInput?: boolean;
    /**
     * Whether arbitrary/custom resolutions are allowed
     */
    supportsCustomResolutions?: boolean;
    /**
     * When true, the model only accepts aspect ratio (e.g., \"16:9\") not pixel dimensions. Auto-detected for known models like google/gemini-3-pro-image-preview.
     */
    usesAspectRatioOnly?: boolean;
    supportedSizes?: Array<string>;
    defaultSize?: string;
    modelConfig?: { [key: string]: any | null; };
    sortOrder?: number;
    /**
     * Credit cost per generation (whole numbers)
     */
    creditCost?: number;
}
export enum CreateImageModelProfileRequestProvider {
    Openai = 'openai',
    Openrouter = 'openrouter',
    Falai = 'falai',
    StableDiffusion = 'stable-diffusion'
};



