/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextModelInfo } from './text-model-info';


/**
 * OpenAI default models
 */
export interface DefaultTextModelsResponseProvidersOpenai { 
    /**
     * Provider display name
     */
    name: string;
    /**
     * Default models
     */
    models: Array<TextModelInfo>;
}

