/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ElementType {

    Folder = 'FOLDER',

    Item = 'ITEM',

    Character = 'CHARACTER',

    Location = 'LOCATION',

    WbItem = 'WB_ITEM',

    Worldbuilding = 'WORLDBUILDING',

    Map = 'MAP',

    Relationship = 'RELATIONSHIP',

    Philosophy = 'PHILOSOPHY',

    Culture = 'CULTURE',

    Species = 'SPECIES',

    Systems = 'SYSTEMS'
}

