/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ElementType {

    Folder = 'FOLDER',

    Item = 'ITEM',

    Worldbuilding = 'WORLDBUILDING',

    RelationshipChart = 'RELATIONSHIP_CHART',

    Canvas = 'CANVAS'
}

