/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FalaiModelMetadata { 
    id: string;
    name: string;
    description: string;
    category: string;
    status: FalaiModelMetadataStatus;
    supportsImageInput: boolean;
    supportsCustomResolutions: boolean;
    supportedSizes: Array<string>;
    supportedAspectRatios: Array<string>;
    supportedResolutions: Array<string>;
    sizeMode: FalaiModelMetadataSizeMode;
}
export enum FalaiModelMetadataStatus {
    Active = 'active',
    Deprecated = 'deprecated'
};
export enum FalaiModelMetadataSizeMode {
    Dimensions = 'dimensions',
    AspectRatio = 'aspect_ratio',
    Unknown = 'unknown'
};



