/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneratedImage { 
    /**
     * Base64-encoded image data
     */
    b64Json?: string;
    /**
     * URL to the image
     */
    url?: string;
    /**
     * Revised prompt if modified
     */
    revisedPrompt?: string;
    /**
     * Image index in batch
     */
    index: number;
    /**
     * Raw text content if the model returned text instead of an image
     */
    textContent?: string;
}

