/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetApiConfigFeatures200ResponseCaptcha } from './get-api-config-features200-response-captcha';


export interface GetApiConfigFeatures200Response { 
    /**
     * Whether AI-powered linting is available
     */
    aiLinting: boolean;
    /**
     * Whether AI-powered image generation is available
     */
    aiImageGeneration: boolean;
    captcha: GetApiConfigFeatures200ResponseCaptcha;
    /**
     * Application mode configuration
     */
    appMode: GetApiConfigFeatures200Response.AppModeEnum;
    /**
     * Default server name to pre-populate in setup form
     */
    defaultServerName?: string;
    /**
     * Whether admin approval is required for new users
     */
    userApprovalRequired: boolean;
}
export namespace GetApiConfigFeatures200Response {
    export const AppModeEnum = {
        Online: 'ONLINE',
        Offline: 'OFFLINE',
        Both: 'BOTH'
    } as const;
    export type AppModeEnum = typeof AppModeEnum[keyof typeof AppModeEnum];
}


