/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetApiV1HealthReady200Response { 
    /**
     * Readiness status
     */
    status: string;
    /**
     * Current server timestamp
     */
    timestamp: string;
}

