/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetImageStatus200Response { 
    /**
     * Whether AI image generation is enabled
     */
    enabled: boolean;
    /**
     * The AI service being used
     */
    service: string;
}

