/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetApiV1ProjectsUsernameSlugCover404Response { 
    /**
     * Error message
     */
    message: string;
}

