/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetSharedFileInfo200Response { 
    filename: string;
    format: string;
    size: number;
    title: string;
    author: string;
    createdAt: string;
}

