/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetApiV1Config200Response { 
    /**
     * Application version
     */
    version: string;
    /**
     * Whether admin approval is required for new users
     */
    userApprovalRequired: boolean;
    /**
     * Whether GitHub OAuth is enabled
     */
    githubEnabled: boolean;
}

