/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { McpPermission } from './mcp-permission';


export interface GetMcpPermissions200ResponsePermissionsInner { 
    id: McpPermission;
    name: string;
    description: string;
    category: GetMcpPermissions200ResponsePermissionsInnerCategory;
}
export enum GetMcpPermissions200ResponsePermissionsInnerCategory {
    Read = 'read',
    Write = 'write'
};



