/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageGenerateRequest { 
    /**
     * The image generation prompt
     */
    prompt: string;
    /**
     * AI model to use
     */
    model?: ImageGenerateRequestModel;
    /**
     * Number of images to generate
     */
    n?: number;
    /**
     * Image quality
     */
    quality?: ImageGenerateRequestQuality;
    /**
     * Response format
     */
    responseFormat?: ImageGenerateRequestResponseFormat;
    /**
     * Image size
     */
    size?: ImageGenerateRequestSize;
    /**
     * Image style
     */
    style?: ImageGenerateRequestStyle;
}
export enum ImageGenerateRequestModel {
    DallE2 = 'dall-e-2',
    DallE3 = 'dall-e-3'
};
export enum ImageGenerateRequestQuality {
    Standard = 'standard',
    Hd = 'hd'
};
export enum ImageGenerateRequestResponseFormat {
    Url = 'url',
    B64Json = 'b64_json'
};
export enum ImageGenerateRequestSize {
    _256x256 = '256x256',
    _512x512 = '512x512',
    _1024x1024 = '1024x1024',
    _1792x1024 = '1792x1024',
    _1024x1792 = '1024x1792'
};
export enum ImageGenerateRequestStyle {
    Vivid = 'vivid',
    Natural = 'natural'
};



