/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageGenerateRequestDto { 
    /**
     * Text description of the desired image(s). Max 32000 chars (gpt-image-1), 1000 (dall-e-2), 4000 (dall-e-3).
     */
    prompt: string;
    /**
     * Model to use: dall-e-2, dall-e-3, or gpt-image-1.
     */
    model?: ImageGenerateRequestDto.ModelEnum;
    /**
     * Number of images to generate (1-10). For dall-e-3, only n=1 is supported.
     */
    n?: number;
    /**
     * Quality of the image (gpt-image-1: high, medium, low; dall-e-3: hd, standard; dall-e-2: standard).
     */
    quality?: ImageGenerateRequestDto.QualityEnum;
    /**
     * Response format (url or b64_json). Not supported for gpt-image-1 (always b64_json).
     */
    response_format?: ImageGenerateRequestDto.ResponseFormatEnum;
    /**
     * Image size (gpt-image-1: 1024x1024, 1536x1024, 1024x1536; dall-e-2: 256x256, 512x512, 1024x1024; dall-e-3: 1024x1024, 1792x1024, 1024x1792).
     */
    size?: ImageGenerateRequestDto.SizeEnum;
    /**
     * Image style (dall-e-3 only): vivid or natural.
     */
    style?: ImageGenerateRequestDto.StyleEnum;
    /**
     * Unique identifier for the end-user to help monitor abuse.
     */
    user?: string;
    /**
     * Background transparency (gpt-image-1 only): transparent, opaque or auto.
     */
    background?: ImageGenerateRequestDto.BackgroundEnum;
    /**
     * Content moderation level (gpt-image-1 only): low or auto.
     */
    moderation?: ImageGenerateRequestDto.ModerationEnum;
    /**
     * Compression level (0-100) for webp/jpeg output (gpt-image-1 only).
     */
    output_compression?: number;
    /**
     * Output format (gpt-image-1 only): png, jpeg, or webp.
     */
    output_format?: ImageGenerateRequestDto.OutputFormatEnum;
}
export namespace ImageGenerateRequestDto {
    export type ModelEnum = 'dall-e-2' | 'dall-e-3' | 'gpt-image-1';
    export const ModelEnum = {
        DallE2: 'dall-e-2' as ModelEnum,
        DallE3: 'dall-e-3' as ModelEnum,
        GptImage1: 'gpt-image-1' as ModelEnum
    };
    export type QualityEnum = 'auto' | 'standard' | 'hd' | 'high' | 'medium' | 'low';
    export const QualityEnum = {
        Auto: 'auto' as QualityEnum,
        Standard: 'standard' as QualityEnum,
        Hd: 'hd' as QualityEnum,
        High: 'high' as QualityEnum,
        Medium: 'medium' as QualityEnum,
        Low: 'low' as QualityEnum
    };
    export type ResponseFormatEnum = 'url' | 'b64_json';
    export const ResponseFormatEnum = {
        Url: 'url' as ResponseFormatEnum,
        B64Json: 'b64_json' as ResponseFormatEnum
    };
    export type SizeEnum = 'auto' | '256x256' | '512x512' | '1024x1024' | '1536x1024' | '1024x1536' | '1792x1024' | '1024x1792';
    export const SizeEnum = {
        Auto: 'auto' as SizeEnum,
        _256x256: '256x256' as SizeEnum,
        _512x512: '512x512' as SizeEnum,
        _1024x1024: '1024x1024' as SizeEnum,
        _1536x1024: '1536x1024' as SizeEnum,
        _1024x1536: '1024x1536' as SizeEnum,
        _1792x1024: '1792x1024' as SizeEnum,
        _1024x1792: '1024x1792' as SizeEnum
    };
    export type StyleEnum = 'vivid' | 'natural';
    export const StyleEnum = {
        Vivid: 'vivid' as StyleEnum,
        Natural: 'natural' as StyleEnum
    };
    export type BackgroundEnum = 'transparent' | 'opaque' | 'auto';
    export const BackgroundEnum = {
        Transparent: 'transparent' as BackgroundEnum,
        Opaque: 'opaque' as BackgroundEnum,
        Auto: 'auto' as BackgroundEnum
    };
    export type ModerationEnum = 'low' | 'auto';
    export const ModerationEnum = {
        Low: 'low' as ModerationEnum,
        Auto: 'auto' as ModerationEnum
    };
    export type OutputFormatEnum = 'png' | 'jpeg' | 'webp';
    export const OutputFormatEnum = {
        Png: 'png' as OutputFormatEnum,
        Jpeg: 'jpeg' as OutputFormatEnum,
        Webp: 'webp' as OutputFormatEnum
    };
}


