/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGenerateResponseRequest } from './image-generate-response-request';
import { ImageProviderType } from './image-provider-type';
import { GeneratedImage } from './generated-image';


export interface ImageGenerateResponse { 
    /**
     * Unix timestamp of creation
     */
    created: number;
    /**
     * Generated images
     */
    data: Array<GeneratedImage>;
    /**
     * Provider that generated the images
     */
    provider: ImageProviderType;
    /**
     * Model used
     */
    model: string;
    request: ImageGenerateResponseRequest;
    /**
     * Raw text content if the model returned text instead of an image (refusal or explanation)
     */
    textContent?: string;
}



