/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollaboratorRole } from './collaborator-role';


export interface InviteCollaboratorRequest { 
    /**
     * Username of user to invite
     */
    username: string;
    /**
     * Role to grant: viewer, editor, or admin
     */
    role: CollaboratorRole;
}



