/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LegalDocumentResponse {
  document: LegalDocumentResponseDocument;
  /**
   * Markdown body, when the document is hosted by Inkweld.
   */
  content?: string;
  /**
   * External page to redirect to, when no hosted text is configured.
   */
  url?: string;
  /**
   * Same token as SystemFeatures.policyVersion.
   */
  version: string;
}
export enum LegalDocumentResponseDocument {
  Privacy = 'privacy',
  Terms = 'terms',
}
