/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponseDto { 
    id: string;
    username: string;
    name: string;
    enabled: boolean;
    sessionId: string;
}

