/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGenerationAudit } from './image-generation-audit';


export interface PaginatedImageAudits { 
    audits: Array<ImageGenerationAudit>;
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}

