/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Passkey } from './passkey';


export interface PasskeyListResponse { 
    passkeys: Array<Passkey>;
}

