/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Passkey {
  id: string;
  /**
   * Base64URL WebAuthn credential ID (for the Signal API)
   */
  credentialId: string;
  name?: string | null;
  deviceType?: string | null;
  backedUp: boolean;
  createdAt: number;
  lastUsedAt?: number | null;
}
