/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PolicyAcceptanceStatus {
  /**
   * Whether the instance requires acceptance at all (REQUIRE_POLICY_ACCEPTANCE).
   */
  required: boolean;
  /**
   * SystemFeatures.policyVersion. Absent when no document is configured.
   */
  currentVersion?: string;
  /**
   * The version this user last accepted, or null if never.
   */
  acceptedVersion: string | null;
  /**
   * Unix seconds when acceptedVersion was recorded, or null.
   */
  acceptedAt: number | null;
  /**
   * True when required and acceptedVersion differs from currentVersion.
   */
  needsAcceptance: boolean;
}
