/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostApiUserRegister200Response { 
    /**
     * Success message
     */
    message: string;
    /**
     * New user ID
     */
    userId: number;
    /**
     * Username
     */
    username: string;
    /**
     * Display name
     */
    name: string;
    /**
     * Whether user requires admin approval
     */
    requiresApproval: boolean;
}


