/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostApiV1AiLint200ResponseStyleRecommendationsInner { 
    /**
     * Style suggestion
     */
    suggestion: string;
    /**
     * Reason for the suggestion
     */
    reason: string;
}

