/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostLint200ResponseCorrectionsInner } from './post-lint200-response-corrections-inner';
import { PostLint200ResponseStyleRecommendationsInner } from './post-lint200-response-style-recommendations-inner';


export interface PostLint200Response { 
    /**
     * The original paragraph
     */
    original_paragraph: string;
    /**
     * List of corrections
     */
    corrections: Array<PostLint200ResponseCorrectionsInner>;
    /**
     * List of style recommendations
     */
    style_recommendations: Array<PostLint200ResponseStyleRecommendationsInner>;
    /**
     * The linting service source
     */
    source: PostLint200Response.SourceEnum;
}
export namespace PostLint200Response {
    export const SourceEnum = {
        Openai: 'openai',
        Languagetool: 'languagetool'
    } as const;
    export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];
}


