/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileVisibility } from './profile-visibility';

export interface ProfileVisibilitySettings {
  profile: ProfileVisibility;
  activity: ProfileVisibility;
  projects: ProfileVisibility;
}
