/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User access permissions for this project
 */
export interface ProjectAccess { 
    /**
     * Whether user is project owner
     */
    isOwner: boolean;
    /**
     * Whether user can read project content
     */
    canRead: boolean;
    /**
     * Whether user can edit project content
     */
    canWrite: boolean;
    /**
     * Whether user can manage project settings and collaborators
     */
    canAdmin: boolean;
    /**
     * Collaborator role if not owner
     */
    role: ProjectAccessRole | null;
}
export enum ProjectAccessRole {
    Viewer = 'viewer',
    Editor = 'editor',
    Admin = 'admin'
};



