/**
 * Worm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectElementDto { 
    /**
     * Unique identifier of the element
     */
    id: string;
    /**
     * Version for optimistic locking
     */
    version: number;
    /**
     * Name of the element
     */
    name: string;
    /**
     * Type of the element (FOLDER/ITEM/IMAGE)
     */
    type: ProjectElementDto.TypeEnum;
    /**
     * Position for ordering elements
     */
    position: number;
    /**
     * Level in the tree hierarchy
     */
    level: number;
    /**
     * Whether the element can be expanded (computed from type)
     */
    expandable: boolean;
    /**
     * Metadata associated with the project element
     */
    metadata: { [key: string]: string; };
}
export namespace ProjectElementDto {
    export type TypeEnum = 'FOLDER' | 'ITEM' | 'IMAGE';
    export const TypeEnum = {
        Folder: 'FOLDER' as TypeEnum,
        Item: 'ITEM' as TypeEnum,
        Image: 'IMAGE' as TypeEnum
    };
}


