/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderStatus { 
    /**
     * Provider identifier
     */
    id: string;
    /**
     * Provider display name
     */
    name: string;
    /**
     * Whether an API key is configured
     */
    hasApiKey: boolean;
    /**
     * Provider description
     */
    description: string;
    /**
     * Whether provider supports image generation
     */
    supportsImages: boolean;
    /**
     * Whether provider supports text generation
     */
    supportsText: boolean;
    /**
     * Whether provider requires a custom endpoint
     */
    requiresEndpoint?: boolean;
    /**
     * Whether a custom endpoint is configured
     */
    hasEndpoint?: boolean;
}

