/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublishEpubResponseDto { 
    /**
     * Original filename of the EPUB file
     */
    originalName: string;
    /**
     * Stored filename of the EPUB file
     */
    storedName: string;
    /**
     * MIME type of the file
     */
    contentType: string;
    /**
     * Size of the file in bytes
     */
    size: number;
    /**
     * Date when the file was created
     */
    uploadDate: string;
}

