/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface QuotaExceededError {
  error: string;
  message?: string;
  code: QuotaExceededErrorCode;
  usedBytes: number;
  quotaBytes: number;
  requiredBytes?: number;
  reason: QuotaExceededErrorReason;
}
export enum QuotaExceededErrorCode {
  QuotaExceeded = 'QUOTA_EXCEEDED',
}
export enum QuotaExceededErrorReason {
  MediaUpload = 'media_upload',
  ProjectCreate = 'project_create',
}
