/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    /**
     * Username (minimum 3 characters)
     */
    username: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Password (minimum 6 characters)
     */
    password: string;
}


