/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    /**
     * Username (minimum 3 characters)
     */
    username: string;
    /**
     * Password (minimum 6 characters)
     */
    password: string;
    /**
     * Email address (optional)
     */
    email?: string;
    /**
     * Display name (optional)
     */
    name?: string;
    /**
     * reCAPTCHA token for verification
     */
    captchaToken?: string;
}

