/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordRequest { 
    /**
     * Password reset token from the emailed link
     */
    token: string;
    /**
     * New password (minimum 6 characters)
     */
    newPassword: string;
}

