/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SnapshotWithContent { 
    id: string;
    documentId: string;
    name: string;
    description?: string | null;
    wordCount?: number | null;
    metadata?: { [key: string]: any | null; } | null;
    createdAt: string;
    yDocState: string;
    stateVector?: string | null;
}

