/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SnapshotDtoCreatedBy } from './snapshot-dto-created-by';


export interface SnapshotDto { 
    /**
     * Unique identifier for the snapshot
     */
    id: string;
    /**
     * The document ID this snapshot belongs to
     */
    documentId: string;
    /**
     * Name of the snapshot
     */
    name: string;
    /**
     * Optional description
     */
    description?: string;
    /**
     * Word count at the time of snapshot
     */
    wordCount?: number;
    /**
     * When the snapshot was created
     */
    createdAt: string;
    createdBy: SnapshotDtoCreatedBy;
    /**
     * Additional metadata
     */
    metadata?: object;
}

