/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageUsageProjectsInner } from './storage-usage-projects-inner';

export interface StorageUsage {
  /**
   * Authoritative storage usage in bytes
   */
  usedBytes: number;
  /**
   * Effective allowance in bytes
   */
  quotaBytes: number;
  /**
   * usedBytes / quotaBytes (null when the allowance is zero)
   */
  fraction: number | null;
  /**
   * True once usage is at or above the allowance
   */
  overQuota: boolean;
  /**
   * True once usage is at or above the warning threshold (80%)
   */
  overSoftLimit: boolean;
  projects: Array<StorageUsageProjectsInner>;
}
