/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StyleRecommendationDto { 
    /**
     * The style recommendation for the paragraph
     */
    suggestion: string;
    /**
     * The reason for the style recommendation
     */
    reason: string;
}

