/**
 * Inkweld API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SurfaceBackground {
  /**
   * Where the image comes from: an admin upload (asset), an external URL (url), or the client\'s bundled default (default).
   */
  source: SurfaceBackgroundSource;
  /**
   * Server-relative API path for `asset`, absolute URL for `url`, null for `default`.
   */
  value: string | null;
}
export enum SurfaceBackgroundSource {
  Default = 'default',
  Asset = 'asset',
  Url = 'url',
}
