/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemStats { 
    /**
     * Total registered users
     */
    userCount: number;
    /**
     * Total projects
     */
    projectCount: number;
    /**
     * Users awaiting approval
     */
    pendingUserCount: number;
    /**
     * Server version
     */
    version: string;
    /**
     * Server uptime in seconds
     */
    uptime: number;
    /**
     * Runtime environment
     */
    runtime: string;
}

