/**
 * Worm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TemplateFieldDto { 
    /**
     * Field identifier
     */
    id: string;
    /**
     * Field name
     */
    name: string;
    /**
     * Field type (references node type)
     */
    type: string;
    /**
     * Whether field is required
     */
    required?: boolean;
    /**
     * Default value
     */
    defaultValue?: object;
    /**
     * View mode
     */
    viewMode?: TemplateFieldDto.ViewModeEnum;
    /**
     * Custom styles
     */
    styles?: object;
}
export namespace TemplateFieldDto {
    export type ViewModeEnum = 'edit' | 'readonly' | 'hidden';
    export const ViewModeEnum = {
        Edit: 'edit' as ViewModeEnum,
        Readonly: 'readonly' as ViewModeEnum,
        Hidden: 'hidden' as ViewModeEnum
    };
}


