/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsernameAvailability { 
    /**
     * Whether username is available
     */
    available: boolean;
    /**
     * Alternative suggestions
     */
    suggestions: Array<string>;
}

