name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation is this regarding?
      options:
        - README/Project overview
        - API documentation
        - Code comments
        - User guide/tutorials
        - Development guides
        - Architecture documentation
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation in question located? (URL, file path, etc.)
      placeholder: e.g., README.md, /docs/api.md, or website URL
    validations:
      required: false

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Formatting/organization issue
        - Other
    validations:
      required: true

  - type: textarea
    id: current_state
    attributes:
      label: Current State
      description: What does the current documentation say or not say?
      placeholder: Please quote the current content if applicable, or describe what's missing
    validations:
      required: true

  - type: textarea
    id: desired_state
    attributes:
      label: Desired State
      description: How should the documentation be improved?
      placeholder: Describe what would make the documentation better, or provide suggested text
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here
      placeholder: Any additional information that might help us understand the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I've checked that this documentation issue hasn't already been reported
          required: true
