/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Original request parameters
 */
export interface ImageGenerateResponseRequest { 
    prompt: string;
    size?: string;
    quality?: string;
    style?: string;
}

