/**
 * Inkweld API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PasskeyRegisterFinishRequest { 
    /**
     * Opaque WebAuthn credential JSON
     */
    response: { [key: string]: any | null; };
    /**
     * Optional user-supplied passkey label
     */
    name?: string;
}

