import { ProjectElement } from './project-tree.component';

export const TREE_DATA: ProjectElement[] = [
  {
    id: 'chapters',
    name: '📖 Chapters',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'c1',
    name: 'Chapter 1',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'c2',
    name: 'Chapter 2',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'chars',
    name: 'Characters',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'ch1',
    name: 'Extras',
    type: 'folder',
    level: 1,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'ce1',
    name: 'Extra A',
    type: 'item',
    level: 2,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ce2',
    name: 'Extra B',
    type: 'item',
    level: 2,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ch1',
    name: 'Character A',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ch2',
    name: 'Character B',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'lo',
    name: 'Locations',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'l1',
    name: 'Location 1',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'l2',
    name: 'Location 2',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
];
