import { ProjectElement } from './ProjectElement';

export const TREE_DATA: ProjectElement[] = [
  {
    id: 'chapters',
    name: 'Chapters',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'c1',
    name: 'Chapter 1',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'c2',
    name: 'Chapter 2',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'chars',
    name: 'Characters',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'extras',
    name: 'Extras',
    type: 'folder',
    level: 1,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'ce1',
    name: 'Extra A',
    type: 'item',
    level: 2,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ce2',
    name: 'Extra B',
    type: 'item',
    level: 2,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ch1',
    name: 'Character A',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'ch2',
    name: 'Character B',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'lo',
    name: 'Locations',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'l1',
    name: 'Location 1',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'l2',
    name: 'Location 2',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
];

export const FILE_ONLY_DATA: ProjectElement[] = [
  {
    id: 'file1',
    name: 'File 1',
    type: 'item',
    level: 0,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'file2',
    name: 'File 2',
    type: 'item',
    level: 0,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'file3',
    name: 'File 3',
    type: 'item',
    level: 0,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'file4',
    name: 'File 4',
    type: 'item',
    level: 0,
    expandable: false,
    expanded: true,
    visible: true,
  },
];

export const SINGLE_FOLDER_DATA: ProjectElement[] = [
  {
    id: 'chapters',
    name: 'Chapters',
    type: 'folder',
    level: 0,
    expandable: true,
    expanded: true,
    visible: true,
  },
  {
    id: 'c1',
    name: 'Chapter 1',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
  {
    id: 'c2',
    name: 'Chapter 2',
    type: 'item',
    level: 1,
    expandable: false,
    expanded: true,
    visible: true,
  },
];
