export * from './embeddingAPI.service';
import { EmbeddingAPIService } from './embeddingAPI.service';
export * from './fileAPI.service';
import { FileAPIService } from './fileAPI.service';
export * from './projectAPI.service';
import { ProjectAPIService } from './projectAPI.service';
export * from './projectElementsAPI.service';
import { ProjectElementsAPIService } from './projectElementsAPI.service';
export * from './userAPI.service';
import { UserAPIService } from './userAPI.service';
export const APIS = [EmbeddingAPIService, FileAPIService, ProjectAPIService, ProjectElementsAPIService, UserAPIService];
