import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';
import {
  screenshotGroups,
  type Screenshot,
  type ScreenshotGroup,
} from './screenshots';
import styles from './styles.module.css';

const FULL_BASE = '/img/';

function srcFor(s: Screenshot): string {
  return `${FULL_BASE}${s.dir}/${s.file}`;
}

/** Flatten groups into a single ordered list for prev/next navigation. */
function flatten(groups: readonly ScreenshotGroup[]): readonly Screenshot[] {
  return groups.flatMap((g) => g.screenshots);
}

interface LightboxState {
  /** Index into the flattened list of currently-visible screenshots. */
  index: number;
  /** The flattened list of currently-visible screenshots. */
  list: readonly Screenshot[];
}

export default function ScreenshotGallery(): React.ReactElement {
  const [query, setQuery] = useState('');
  const [showLabels, setShowLabels] = useState(true);
  const [showMissing, setShowMissing] = useState(true);
  const [lightbox, setLightbox] = useState<LightboxState | null>(null);

  // Track which images failed to load so we can render a placeholder.
  const [broken, setBroken] = useState<Set<string>>(() => new Set());
  const markBroken = useCallback((src: string) => {
    setBroken((prev) => {
      if (prev.has(src)) return prev;
      const next = new Set(prev);
      next.add(src);
      return next;
    });
  }, []);
  const markOk = useCallback((src: string) => {
    setBroken((prev) => {
      if (!prev.has(src)) return prev;
      const next = new Set(prev);
      next.delete(src);
      return next;
    });
  }, []);

  const filteredGroups = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return screenshotGroups;
    return screenshotGroups
      .map((g) => ({
        ...g,
        screenshots: g.screenshots.filter(
          (s) =>
            s.label.toLowerCase().includes(q) ||
            s.file.toLowerCase().includes(q) ||
            g.title.toLowerCase().includes(q)
        ),
      }))
      .filter((g) => g.screenshots.length > 0);
  }, [query]);

  const flatList = useMemo(() => flatten(filteredGroups), [filteredGroups]);

  const totalScreenshots = useMemo(() => flatten(screenshotGroups).length, []);
  const visibleCount = flatList.length;
  const missingCount = useMemo(
    () => flatList.filter((s) => broken.has(srcFor(s))).length,
    [flatList, broken]
  );

  const openLightbox = useCallback(
    (s: Screenshot) => {
      const idx = flatList.findIndex(
        (x) => x.file === s.file && x.dir === s.dir
      );
      if (idx >= 0) setLightbox({ index: idx, list: flatList });
    },
    [flatList]
  );

  const closeLightbox = useCallback(() => setLightbox(null), []);

  const stepLightbox = useCallback((delta: number) => {
    setLightbox((prev) => {
      if (!prev) return prev;
      const next = prev.index + delta;
      if (next < 0 || next >= prev.list.length) return prev;
      return { ...prev, index: next };
    });
  }, []);

  // Keyboard navigation for the lightbox.
  useEffect(() => {
    if (!lightbox) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeLightbox();
      else if (e.key === 'ArrowLeft') stepLightbox(-1);
      else if (e.key === 'ArrowRight') stepLightbox(1);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [lightbox, closeLightbox, stepLightbox]);

  // Lock body scroll while the lightbox is open.
  useEffect(() => {
    if (!lightbox) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [lightbox]);

  const current = lightbox ? lightbox.list[lightbox.index] : null;

  return (
    <Layout
      title="Screenshot Gallery"
      description="Visual reference gallery of every screenshot produced by the Inkweld screenshot e2e suite."
    >
      <div className={styles.galleryHeader}>
        <Heading as="h1">Screenshot Gallery</Heading>
        <p className={styles.galleryIntro}>
          Every screenshot generated by the screenshot e2e suite, laid out for
          quick scanning. Click any thumbnail to open a full-size lightbox — use
          the arrow keys to move between screenshots. Missing images appear
          greyed out until the suite is run.
        </p>
        <p className={styles.stats}>
          {totalScreenshots} screenshots across {screenshotGroups.length} groups
          {visibleCount !== totalScreenshots
            ? ` · ${visibleCount} matching`
            : ''}
          {missingCount > 0 ? ` · ${missingCount} not yet generated` : ''}
        </p>
      </div>

      <div className={styles.controls}>
        <input
          className={styles.search}
          type="search"
          placeholder="Filter by group, label, or filename…"
          value={query}
          aria-label="Filter screenshots"
          onChange={(e) => setQuery(e.target.value)}
        />
        <button
          type="button"
          className={showLabels ? styles.toggleActive : styles.toggle}
          onClick={() => setShowLabels((v) => !v)}
          aria-pressed={showLabels}
        >
          {showLabels ? 'Labels on' : 'Labels off'}
        </button>
        <button
          type="button"
          className={showMissing ? styles.toggleActive : styles.toggle}
          onClick={() => setShowMissing((v) => !v)}
          aria-pressed={showMissing}
          title="Show or hide screenshots that have not been generated yet"
        >
          {showMissing ? 'Missing: shown' : 'Missing: hidden'}
        </button>
      </div>

      <main className="container">
        {filteredGroups.length === 0 ? (
          <p className={styles.empty}>No screenshots match “{query}”.</p>
        ) : (
          filteredGroups.map((group) => (
            <section key={group.title} className={styles.group}>
              <Heading as="h2" className={styles.groupTitle}>
                {group.title}
                <span className={styles.groupCount}>
                  {group.screenshots.length} screenshot
                  {group.screenshots.length === 1 ? '' : 's'}
                </span>
              </Heading>
              {group.description ? (
                <p className={styles.groupDesc}>{group.description}</p>
              ) : null}
              <div className={styles.grid}>
                {group.screenshots.map((s) => {
                  const src = srcFor(s);
                  const isBroken = broken.has(src);
                  if (!showMissing && isBroken) return null;
                  return (
                    <button
                      type="button"
                      key={src}
                      className={styles.card}
                      onClick={() => openLightbox(s)}
                      aria-label={`Open ${s.label} full size`}
                    >
                      <div className={styles.thumb}>
                        {isBroken ? (
                          <div className={styles.thumbBroken}>
                            <span>⚠️ Not generated</span>
                            <code>{s.file}</code>
                          </div>
                        ) : (
                          <img
                            className={styles.thumbImg}
                            src={src}
                            alt={s.label}
                            loading="lazy"
                            onError={() => markBroken(src)}
                            onLoad={() => markOk(src)}
                          />
                        )}
                      </div>
                      {showLabels ? (
                        <div className={styles.label}>
                          {s.label}
                          <div className={styles.path}>
                            {s.dir}/{s.file}
                          </div>
                        </div>
                      ) : null}
                    </button>
                  );
                })}
              </div>
            </section>
          ))
        )}
      </main>

      {lightbox && current ? (
        <div className={styles.lightboxBackdrop}>
          <dialog className={styles.lightbox} aria-label={current.label} open>
            <div className={styles.lightboxBar}>
              <div>
                <div className={styles.lightboxLabel}>{current.label}</div>
                <div className={styles.lightboxPath}>
                  {current.dir}/{current.file}
                </div>
              </div>
              <div className={styles.lightboxNav}>
                <span className={styles.lightboxCounter}>
                  {lightbox.index + 1} / {lightbox.list.length}
                </span>
                <button
                  type="button"
                  className={styles.lightboxBtn}
                  onClick={() => stepLightbox(-1)}
                  disabled={lightbox.index === 0}
                  aria-label="Previous screenshot"
                >
                  ← Prev
                </button>
                <button
                  type="button"
                  className={styles.lightboxBtn}
                  onClick={() => stepLightbox(1)}
                  disabled={lightbox.index === lightbox.list.length - 1}
                  aria-label="Next screenshot"
                >
                  Next →
                </button>
                <button
                  type="button"
                  className={styles.lightboxBtn}
                  onClick={closeLightbox}
                  aria-label="Close lightbox"
                >
                  Close
                </button>
              </div>
            </div>
            <div className={styles.lightboxStage}>
              <img
                className={styles.lightboxImg}
                src={srcFor(current)}
                alt={current.label}
              />
            </div>
          </dialog>
        </div>
      ) : null}
    </Layout>
  );
}
